version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:  # Usar el archivo `.env` para las variables de entorno
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.4.0
    env_file:  # Usar el archivo `.env` para las variables de entorno
      - .env
    ports:
      - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:
